### ISSUE TITLE
Changelog uses date from wrong tag for release message

### ISSUE THREAD

**Issue by j4zz** [iv-mexx/git-changelog#2]
When calling git-changelog for my project like this: `git-changelog 0.9.0 0.8.0 --format slack` it contains a line like the following: `Version 0.9.0 (_03.09.2015_)`

But `03.09.2015` is in fact the date of the tag `0.8.0`. Instead, I would have expected it to pick up the date from the tag `0.9.0`, which would be `17.09.2015`.

I think the cause may be [this line](https://github.com/iv-mexx/git-changelog/blob/develop/lib/changelog_helpers.rb#L81) and [this line](https://github.com/iv-mexx/git-changelog/blob/develop/lib/changelog_helpers.rb#L114) (this should probably be DRYed up by abstracting the information retrieval to a new class for example), which should be `str << " (_#{@commit_from.time.strftime("%d.%m.%Y")}_)"` (`from` instead of `to`) instead.

**Comment by iv-mexx** [comment]
The bug has been fixed in #5, but I agree that this should still be DRYed up.
